### ISSUE TITLE
Add number of posts

### ISSUE THREAD

**Issue by iggyvolz** [iggyvolz/FM-Bot#1]
Get number of posts on thread.

**Comment by Coolway99** [comment]
I posted this in skype, but I'll copy/paste it here as well:

[11:08:54 AM] Coolway99: hey, so I'm going through the html doccument to try and help you in your task...

first off, you have an empty link, <a name="start_here"></a>, that skips most of the title stuff

Every post is seperated with a horizontal rule by the name of divider, html wise, <hr class="divider">

[11:10:01 AM] Coolway99: So to get the number of posts, all you have to do is get the number of times <hr class="divider"> appears

**Comment by Coolway99** [comment]
(Yes I deleted my previous comment because the html was parsing)
I figured this is worth posting here as well:
[11:08:54 AM] Coolway99: hey, so I'm going through the html doccument to try and help you in your task...

first off, you have an empty link, &lt;a name="start_here">&lt;/a>, that skips most of the title stuff

Every post is seperated with a horizontal rule by the name of divider, html wise, &lt;hr class="divider">
[11:10:01 AM] Coolway99: So to get the number of posts, all you have to do is get the number of times &lt;hr class="divider"> appears

I should note that the way that the posts are, &lt;hr class="divider"> appears even if the post is the last one on the page.

**Comment by Coolway99** [comment]
So, upon further inspection it's safer to search for it without the >, but I made a little java program that sniffs the page for how many posts, if that helps

**Comment by iggyvolz** [comment]
I actually meant getting the "XXX posts" from the page for this issue.

Currently how I do it is sending a request to &start=XXX and only getting the first post, but it would be much more efficient to get all of the posts from the page.

**Comment by iggyvolz** [comment]
Finished this a while ago, forgot to close.
